# Generated by Django 6.0.7 on 2026-07-14 10:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_store_plan_delete_subscriptionplan'),
        ('website_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='animation_type',
            field=models.CharField(blank=True, default='fade', max_length=50),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='badge',
            field=models.CharField(blank=True, help_text="e.g. 'HOT DEAL' or 'NEW ARRIVAL'", max_length=100),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='countdown_end',
            field=models.DateTimeField(blank=True, help_text='Optional event countdown timer end date', null=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_slides/mobile/'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='overlay_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='text_color',
            field=models.CharField(default='#000000', help_text="CSS Color code e.g. '#ffffff' or 'white'", max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome icon class name (e.g. 'fa-laptop')", max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website_management.menuitem'),
        ),
        migrations.AddField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/featured/'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/hero/'),
        ),
        migrations.AddField(
            model_name='page',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text="e.g. '#f8f9fa' or 'black'", max_length=20),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/mobile/'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='text_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_transfer_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cart_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cod_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='search_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sticky_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wishlist_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='position',
            field=models.CharField(choices=[('home_top', 'Home — Top'), ('home_middle', 'Home — Middle'), ('home_bottom', 'Home — Bottom'), ('category_page', 'Category Page'), ('product_page', 'Product Page'), ('sidebar', 'Sidebar'), ('footer', 'Footer')], default='home_top', max_length=30),
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('section_key', models.CharField(choices=[('slider', 'Hero Banner Slider'), ('categories', 'Featured Categories'), ('featured_products', 'Featured Products Grid'), ('new_arrivals', 'New Arrivals Grid'), ('top_selling', 'Top Selling Grid'), ('sale_products', 'Discounted Items Grid'), ('middle_banners', 'Promotional Banners Row'), ('reviews', 'Customer Testimonials')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.store')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('file', models.ImageField(upload_to='media_library/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
