# Generated by Django 6.0.7 on 2026-07-24 05:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_store_plan_delete_subscriptionplan'),
        ('website_management', '0002_heroslide_alt_text_heroslide_animation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_1_text',
            field=models.CharField(blank=True, default='On orders over $50', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_1_title',
            field=models.CharField(blank=True, default='Free Shipping', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_2_text',
            field=models.CharField(blank=True, default='Always here to help', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_2_title',
            field=models.CharField(blank=True, default='24/7 Support', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_3_text',
            field=models.CharField(blank=True, default='100% protected', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_3_title',
            field=models.CharField(blank=True, default='Secure Payments', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_4_text',
            field=models.CharField(blank=True, default='30-day policy', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_4_title',
            field=models.CharField(blank=True, default='Easy Returns', max_length=80),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
