# Generated by Django 6.0.7 on 2026-07-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_store_plan_delete_subscriptionplan'),
        ('website_management', '0003_sitesettings_feature_1_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_key',
            field=models.CharField(choices=[('slider', 'Hero Banner Slider'), ('categories', 'Featured Categories'), ('featured_products', 'Featured Products Grid'), ('new_arrivals', 'New Arrivals Grid'), ('top_selling', 'Top Selling Grid'), ('sale_products', 'Discounted Items Grid'), ('middle_banners', 'Promotional Banners Row'), ('reviews', 'Customer Testimonials')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='homepagesection',
            unique_together={('store', 'section_key')},
        ),
    ]
