# Generated by Django 6.0.7 on 2026-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management', '0004_alter_homepagesection_section_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_key',
            field=models.CharField(choices=[('slider', 'Hero Banner Slider'), ('categories', 'Featured Categories'), ('featured_products', 'Featured Products Grid'), ('new_arrivals', 'New Arrivals Grid'), ('top_selling', 'Top Selling Grid'), ('sale_products', 'Discounted Items Grid'), ('middle_banners', 'Promotional Banners Row'), ('reviews', 'Customer Testimonials'), ('special_offers', 'Special Offers'), ('recently_added', 'Recently Added'), ('flash_sale', 'Flash Sale'), ('trending_products', 'Trending Products'), ('brands', 'Brands')], max_length=50),
        ),
    ]
