# Generated by Django 6.0.7 on 2026-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('website_management', '0005_alter_homepagesection_section_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='homepage_sections', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_key',
            field=models.CharField(choices=[('slider', 'Hero Banner Slider'), ('categories', 'Featured Categories'), ('featured_products', 'Featured Products Grid'), ('new_arrivals', 'New Arrivals Grid'), ('top_selling', 'Top Selling Grid'), ('sale_products', 'Discounted Items Grid'), ('middle_banners', 'Promotional Banners Row'), ('reviews', 'Customer Testimonials'), ('special_offers', 'Special Offers'), ('recently_added', 'Recently Added'), ('flash_sale', 'Flash Sale'), ('trending_products', 'Trending Products'), ('deal_of_the_day', 'Deal of the Day'), ('why_choose_us', 'Why Choose Us'), ('brands', 'Brands'), ('newsletter', 'Newsletter')], max_length=50),
        ),
    ]
