# Generated by Django 6.0.7 on 2026-07-25 10:34

import website_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management', '0006_homepagesection_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to=website_management.models.hero_slide_upload_to),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to=website_management.models.hero_slide_mobile_upload_to),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.ImageField(upload_to=website_management.models.media_library_upload_to),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='image',
            field=models.ImageField(upload_to=website_management.models.banner_upload_to),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to=website_management.models.banner_mobile_upload_to),
        ),
    ]
