# Generated by Django 6.0.7 on 2026-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management', '0007_alter_heroslide_image_alter_heroslide_mobile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_key',
            field=models.CharField(choices=[('slider', 'Hero Banner Slider'), ('sales_strip', 'Mega Sales Banner Strip (Daraz Style)'), ('categories', 'Featured Categories'), ('featured_products', 'Featured Products Grid'), ('new_arrivals', 'New Arrivals Grid'), ('top_selling', 'Top Selling Grid'), ('sale_products', 'Discounted Items Grid'), ('middle_banners', 'Promotional Banners Row'), ('reviews', 'Customer Testimonials'), ('special_offers', 'Special Offers'), ('recently_added', 'Recently Added'), ('flash_sale', 'Flash Sale'), ('trending_products', 'Trending Products'), ('deal_of_the_day', 'Deal of the Day'), ('why_choose_us', 'Why Choose Us'), ('brands', 'Brands'), ('newsletter', 'Newsletter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='position',
            field=models.CharField(choices=[('home_top', 'Home — Top (Hero Right Side)'), ('sales_strip', 'Home — Mega Sales Banner Strip (Daraz Style)'), ('home_middle', 'Home — Middle (Special Offers)'), ('home_bottom', 'Home — Bottom (Bottom Grid)'), ('app_promo', 'Home — App Download / Voucher Banner Widget'), ('category_page', 'Category Page'), ('product_page', 'Product Page'), ('sidebar', 'Sidebar'), ('footer', 'Footer')], default='home_top', max_length=30),
        ),
    ]
