# Generated by Django 6.0.7 on 2026-07-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_store_created_at_alter_store_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='plan',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
