# Generated by Django 6.0.7 on 2026-07-25 10:34

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_store_plan_delete_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.store_banner_upload_to),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.store_logo_upload_to),
        ),
    ]
