# Generated by Django 6.0.7 on 2026-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Platform Super Admin'), ('owner', 'Store Owner'), ('manager', 'Store Manager'), ('cashier', 'Cashier / POS Operator'), ('inventory_staff', 'Inventory Staff'), ('support', 'Support / Customer Service'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
