# Generated by Django 6.0.7 on 2026-07-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('online', 'Online Storefront')], default='online', max_length=10),
        ),
    ]
